### ISSUE TITLE
Recursive tidy's can stack up and cause performance problems

### ISSUE THREAD

**Issue by mhjacks** [npwalker/pe_metric_curl_cron_jobs#3]
Hi Nick,

We have found that recursive tidy can be very expensive - our MoM's have OOM'ed because too many tidy processes were active at once.  (Granted, we have a lot of files to tidy.)

What I'd like to suggest is that we use a more traditional find with mtime (which should be available on all PE Master platforms), e.g. find <dir> -type f -mtime <days> -delete.  I'll submit a PR for that this weekend.

**Comment by npwalker** [comment]
Resolved by https://github.com/npwalker/pe_metric_curl_cron_jobs/pull/4
