### ISSUE TITLE
Cron jobs send email on every run

### ISSUE THREAD

**Issue by tgm4883** [npwalker/pe_metric_curl_cron_jobs#32]
Cron jobs send email on every run, even if they run without error.

**Comment by tgm4883** [comment]
[1.patch.txt](https://github.com/npwalker/pe_metric_curl_cron_jobs/files/977212/1.patch.txt)

**Comment by tgm4883** [comment]
This patch should resolve that.

**Comment by jarretlavallee** [comment]
The code has changed a good amount since the last released forge version. The emails should not be showing up after #28

**Comment by tgm4883** [comment]
Nice, the new version works much better it seems.
