### ISSUE TITLE
Provide utility command to collect metrics archive for submission/transport

### ISSUE THREAD

**Issue by reidmv** [npwalker/pe_metric_curl_cron_jobs#40]
We should provide a CLI utility shipped in this module which simplifies the task of scooping up all the collected metrics into a tarball to send to Support or otherwise transfer off the collecting system. E.g.

`puppet metrics-collector create-tarball <filename>`

This would simplify the instructions we give customers who use the tool and need to send us back the data for analysis.

**Comment by npwalker** [comment]
Are you implying it should actually be a puppet face?  As opposed to a bash script in `/opt/puppetlabs/pe_metric_curl_cron_jobs/scripts`?

**Comment by reidmv** [comment]
Nope. Shouldn't be a face. I used Puppet syntax wherein if the script is of the form `puppet-thing`, you can invoke it as `puppet thing` IIF the directory containing the bash script is in PATH. So maybe:

```
/opt/puppetlabs/bin/puppet-metrics-collector create-tarball <filename>
```

Substitute another directory if we aren't comfortable with using `/opt/puppetlabs/bin`.
